FROM python:3.8

RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

COPY display.py /app/display.py

CMD ["bokeh", "serve", "--port", "8081", "--num-procs", "3", "/app/display.py"]
